# Use this template for all examples except for
# ccloud_standard_kafka_producer.py and
# ccloud_standard_kafka_consumer.py
app_id: XXXXX-YYYY-AAA-BBBB-CCCCCCCCCCCC
pool_id: pool-ABCD
env_id: t1234556
cluster_id: 123456
topic: test
client_id: example
consumer_group_id: example
#debug_azure_authentication: True
# Managed identities are only useful when the code runs on Azure.
# Disabling them can speed up the login procedure on machines not running on Azure, e.g. developer machines
#exclude_managed_identity_credential: True